---
- name: Update pacman repositories cache
  pacman:
    update_cache: yes
  changed_when: false
  when: ansible_pkg_mgr == "pacman"

- name: Install pacman packages
  pacman:
    name: "{{ item }}"
  with_items:
    - postgresql
    - postgresql-docs
    - postgresql-old-upgrade
    - python2-psycopg2
  when: ansible_pkg_mgr == "pacman"

- name: Update apt repositories cache
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_pkg_mgr == "apt"

- name: Install apt packages
  apt:
    name: "{{ item }}"
  with_items:
    - postgresql
    - postgresql-client
    - postgresql-doc
    - python-psycopg2
  register: apt
  when: ansible_pkg_mgr == "apt"

- name: Stop PostgreSQL
  service:
    name: postgresql.service
    state: stopped
  when: ansible_pkg_mgr == "apt" and apt.changed

- name: Get postgresql version
  shell: "dpkg-query --showformat='${Version}' --show postgresql | cut -d'+' -f1"
  changed_when: false
  register: pg_ver
  when: ansible_pkg_mgr == "apt"

- name: Delete default postgres unit
  file:
    path: /lib/systemd/system/postgresql@.service
    state: absent
  register: del_unit
  when: ansible_pkg_mgr == "apt"

- name: Stop default postgres unit
  service:
    name: "postgresql@{{ pg_ver.stdout }}{% if ansible_distribution == 'Debian' %}-main{% endif %}.service"
    state: stopped
    enabled: false
  when: ansible_pkg_mgr == "apt" and del_unit.changed

- name: Reload systemd
  systemd:
    daemon_reload: true
  when: del_unit.changed

- name: Ensure Postgres group exists
  group:
    name: "{{ postgres_group }}"
    system: true

- name: Ensure Postgres user exists
  user:
    name: "{{ postgres_user }}"
    group: "{{postgres_group }}"
    shell: /bin/false
    home: "{{ postgres_home_directory }}"
    comment: "PostgreSQL user"
    createhome: false
    system: true

- name: Create configuration directory
  file:
    path: "{{ postgres_conf_directory }}"
    state: directory
    mode: 0750
    owner: root
    group: postgres

- name: Create directoreies
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"
  with_items:
    - "{{ postgres_data_directory }}"
    - "{{ postgres_log_directory }}"
    - "{{ postgres_home_directory }}"

- name: Set path to postgres utilities
  set_fact:
    "{{ item.name }}": "{% if pg_ver.stdout %}/usr/lib/postgresql/{{ pg_ver.stdout }}/bin/{{ item.value }}{% else %}{{ item.default }}{% endif %}"
  when: "{{ item.name }} is not defined"
  with_items:
    - name: postgres_initdb
      value: initdb
      default: postgres_default_initdb
    - name: postgres_pg_ctl
      value: pg_ctl
      default: postgres_default_pg_ctl
